# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
ntitle:           Spencer
tagline:          'Spencer'
description:      'Spencer'
baseurl:          /

author:
  name:           'Spencer'

paginate:         5

# Custom vars

gems: [jekyll-paginate, jekyll-gist]
